name: build-go-binary

on:
  release:
    types: [created, published] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史（某些工具需要）

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # 或你项目所需的版本

      - name: Run Go Release Action
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux,darwin,windows
          goarch: amd64,arm64
          goversion: 1.22.0
          binary_name: "cdpnettool"
          ldflags: "-s -w"
          extra_files: LICENSE README.md wails.json        
